
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import useReports from "@/hooks/useReports"
// Status badge component
const StatusBadge = ({ status }: { status: string }) => {
  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case "delivered":
        return "bg-green-100 text-green-800"
      case "pending":
        return "bg-yellow-100 text-yellow-800"
      case "confirmed":
        return "bg-blue-100 text-blue-800"
      case "dispatched":
        return "bg-purple-100 text-purple-800"
      case "canceled":
        return "bg-red-100 text-red-800"
      default:
        return "bg-gray-100 text-gray-800"
    }
  }

  return (
    <span className={`px-3 py-1 rounded-full text-xs font-medium ${getStatusColor(status)}`}>
      {status.charAt(0).toUpperCase() + status.slice(1)}
    </span>
  )
}

// Simplified order report component
export default function SimplifiedOrderReport() {
  const { ordersReport } = useReports();
  // Sample data for demo purposes

  const displayOrders = ordersReport || [];

  return (
    <div className="p-8 max-w-4xl mx-auto bg-white">
      <h1 className="text-2xl font-bold text-blue-800 mb-6">Order Report</h1>
      <Table>
        <TableCaption>
          Order Report - Generated {new Date().toLocaleDateString()}
        </TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead>Order #</TableHead>
            <TableHead>Customer ID</TableHead>
            <TableHead>Date</TableHead>
            <TableHead>Amount</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Payment Method</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {displayOrders.map((order) => (
            <TableRow key={order.id}>
              <TableCell className="font-medium text-blue-800">
                #{order.order_number}
              </TableCell>
              <TableCell className="text-black">{order.user_id}</TableCell>
              <TableCell className="text-black">
                {order.created_at
                  ? new Date(order.created_at).toLocaleDateString()
                  : "N/A"}
              </TableCell>
              <TableCell className="font-medium text-green-600">
                {order.total_price}
              </TableCell>
              <TableCell>
                <StatusBadge status={order.status || "pending"} />
              </TableCell>
              <TableCell className="text-black">
                {order.payment_method || "N/A"}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      <div className="mt-4 text-gray-500 text-sm text-center">
        Generated by Farmsell. Contact: williams@tallenhub.com
      </div>
    </div>
  );
}